language: cpp
dist: xenial
compiler: clang
before_script:
  - sudo apt-get install libboost-test-dev -y
script:
  - mkdir build
  - cd build
  - cmake ../
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T ip_filter_pkg-*.$TRAVIS_BUILD_NUMBER-Linux.deb -utatyana-otus:$BINTRAY_API_KEY "https://api.bintray.com/content/tatyana-otus/hw_otus/test/$TRAVIS_BUILD_NUMBER/ip_filter_pkg-1.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"





